container:
    dockerfile: .cirrus_Dockerfile

build_task:
    # set timeout so that we don't die halfway through build
    timeout_in: 120m
    # we need to explicitly use local-git and not cirrus go-git (cmake doesn't like it)
    clone_script: |
        if [ -z "$CIRRUS_PR" ]; then
            git clone --recursive --branch=$CIRRUS_BRANCH https://x-access-token:${CIRRUS_REPO_CLONE_TOKEN}@github.com/${CIRRUS_REPO_FULL_NAME}.git $CIRRUS_WORKING_DIR
            git reset --hard $CIRRUS_CHANGE_IN_REPO
        else
            git clone --recursive https://x-access-token:${CIRRUS_REPO_CLONE_TOKEN}@github.com/${CIRRUS_REPO_FULL_NAME}.git $CIRRUS_WORKING_DIR
            git fetch origin pull/$CIRRUS_PR/head:pull/$CIRRUS_PR
            git reset --hard $CIRRUS_CHANGE_IN_REPO
        fi
    build_script:
        - mkdir -p ~/.sac2crc
        - mkdir build && cd build
        - cmake -DFULLTYPES=ON -DLINKSETSIZE=250 ..
        # we need to test that make actually completed:
        - make -j3 2>&1 | tee build.log
        - if [ ${PIPESTATUS[0]} -ne 0 ]; then
            echo "!!! ERROR detected in build !!!";
            exit 1;
          fi
        - if [ $(grep -i 'warning' build.log | wc -l) -gt 0 ]; then
            echo "+++ ${WARN_NUM} warnings detected +++";
            grep -i 'warning' build.log;
            exit 1;
          fi
