# The following configuration is used to setup GitHub Actions
# for building (and running unit tests) on pushes and PRs.
# At the moment, we build on two runner types: Linux and MacOS,
# specific version information can be found further below.
name: Build On Changes

on: [pull_request]

env:
  SAC2C_URL: https://gitlab.sac-home.org/sac-group/sac2c.git
  INTTEST_URL: https://github.com/SacBase/IntegrationTests.git

jobs:
  build-ubuntu26:
    runs-on: ubuntu-26.04
    container:
      image: nvidia/cuda:13.3.1-devel-ubuntu26.04
    steps:
    - name: Install dependencies
      run: |
        apt-get update
        apt-get install -y \
          git \
          cmake \
          ninja-build \
          ca-certificates \
          libhwloc-dev \
          uuid-runtime \
          uuid-dev \
          xsltproc \
          bison \
          flex \
          m4
    - name: Get HEAD and submodules
      uses: actions/checkout@v6
      with:
        fetch-depth: 0
        submodules: 'recursive'
    - name: Install sac2c
      run: |
        git clone --single-branch --recursive ${SAC2C_URL} sac2c
        cd sac2c
        cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=RELEASE -DCUDA=ON
        cmake --build build --parallel
        ln -s $PWD/build/sac2c_p /usr/local/bin/sac2c
        sac2c -V
    - name: Configure build system
      run: |
        cmake -S . -B build -G Ninja \
          -DTARGETS="seq;seq_checks;mt_pth;cuda" \
          -DBUILD_EXT=ON \
          -DLINKSETSIZE=200
    - name: Build
      shell: bash
      run: |
        cmake --build build --parallel 2>&1 | tee build.log
        if [ ${PIPESTATUS[0]} -ne 0 ]; then
          echo "!!! ERROR detected in build !!!";
          exit 1;
        fi
        ${GITHUB_WORKSPACE}/ci/fail-on-warning.sh build.log
    - name: Test
      shell: bash
      run: |
        git clone --single-branch --recursive ${INTTEST_URL} inttest
        cd inttest
        make all
        ./test.sh

  build-macos-arm:
    runs-on: macos-latest
    steps:
    - name: Install dependencies
      run: |
        brew update
        brew install libxslt
    - name: Get HEAD and submodules
      uses: actions/checkout@v6
      with:
        fetch-depth: 0
        submodules: 'recursive'
    - name: Set XCode version
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
    - name: Install sac2c
      run: |
        git clone --single-branch --recursive ${SAC2C_URL} sac2c
        cd sac2c
        cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=RELEASE
        cmake --build build --parallel
        ln -s $PWD/build/sac2c_p /usr/local/bin/sac2c
        sac2c -V
    - name: Configure build system
      run: |
        cmake -S . -B build -G Ninja \
          -DTARGETS="seq;seq_checks;mt_pth" \
          -DBUILD_EXT=ON
    - name: Build
      shell: bash
      run: |
        cmake --build build --parallel 2>&1 | tee build.log
        if [ ${PIPESTATUS[0]} -ne 0 ]; then
          echo "!!! ERROR detected in build !!!";
          exit 1;
        fi
        ${GITHUB_WORKSPACE}/ci/fail-on-warning.sh build.log
    - name: Test
      shell: bash
      run: |
        git clone --single-branch --recursive ${INTTEST_URL} inttest
        cd inttest
        make all
        ./test.sh
